apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: 167698347898.dkr.ecr.eu-west-1.amazonaws.com/apache-bitbucket-container
        imagePullPolicy: Always
        ports:
        - containerPort: 80
